services:
  - type: web
    name: clavis-web
    runtime: static
    staticPublishPath: ./web
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /confirm
        destination: /confirm.html

